version: "3"
services:
  server:
    image: gocd/gocd-server:v19.3.0

    ports:
      - "8153:8153"
      - "8154:8154"

    volumes:
      - ./data:/godata
      - ./data/home:/home/go
      - ./scripts/server:/docker-entrypoint.d
      - ./scripts/shared:/shared

    environment:
      - JAVA_TOOL_OPTIONS=
        -XX:+UnlockExperimentalVMOptions
        -XX:+UseCGroupMemoryLimitForHeap
        -XX:+UseParallelGC
        -XX:MinHeapFreeRatio=5
        -XX:MaxHeapFreeRatio=10
        -XX:GCTimeRatio=4
        -XX:AdaptiveSizePolicyWeight=90
      - GO_SERVER_SYSTEM_PROPERTIES=
        -Dcruise.material.update.interval=2000
        -Dmaterial.update.idle.interval=2000
      - CONFIG_GIT_REPO=https://github.com/TimJDFletcher/example-gocd-pipelines.git
      - CONFIG_GIT_BRANCH=master

  agent:
    image: gocd/gocd-agent-alpine-3.8:v19.3.0

    environment:
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
      - GO_SERVER_URL=https://server:8154/go
      - AGENT_AUTO_REGISTER_KEY=agent-autoregister-key
      - JAVA_TOOL_OPTIONS=
        -XX:+UnlockExperimentalVMOptions
        -XX:+UseCGroupMemoryLimitForHeap
        -XX:+UseParallelGC
        -XX:MinHeapFreeRatio=5
        -XX:MaxHeapFreeRatio=10
        -XX:GCTimeRatio=4
        -XX:AdaptiveSizePolicyWeight=90
    volumes:
      - ./scripts/agent:/docker-entrypoint.d
      - ./scripts/shared:/shared

    deploy:
      replicas: 2

    depends_on:
      - "server"
